create Table Author(
	AuthorID INTEGER PRIMARY KEY,
	LastName TEXT NOT NULL,
	FirstName TRXT NOT NULL,
	Nationality TEXT NOT NULL
);
CREATE TABLE Copy(
	CopyNo INTEGER PRIMARY KEY,
	ShelfLocation TEXT NOT NULL,
	Conditon TEXT NOT NULL,
	isbn INTEGER NOT NULL,
	FOREIGN KEY (isbn) REFERENCES Book(ISBN)
		ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE Book(
	ISBN Text PRIMARY KEY,
	Title TEXT NOT NULL,
	PublicationYear INTEGER NOT NULL
);
CREATE TABLE Member(
	MemberNo INTEGER PRIMARY KEY,
	LastName TEXT NOT NULL,
	FirstName TEXT NOT NULL,
	EMAIL TEXT NOT NULL,
	EnrolmentDate DATE NOT NULL
);
CREATE TABLE Loan(
	LoanID INTEGER PRIMARY KEY,
	LoanDate DATE NOT NULL,
	ReturnDate DATE,
	member_no INTEGER,
	copy_no INTEGER,
	FOREIGN KEY (member_no) REFERENCES Member(MemberNo)
        	ON DELETE RESTRICT ON UPDATE CASCADE,
    	FOREIGN KEY (copy_no) REFERENCES Copy(CopyNo)
        	ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE writes (
    author_id INTEGER NOT NULL,
    isbn      TEXT    NOT NULL,
    PRIMARY KEY (author_id, isbn),
    FOREIGN KEY (author_id) REFERENCES Author(AuthorID)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (isbn)      REFERENCES Book(ISBN)
        ON DELETE RESTRICT ON UPDATE CASCADE
);


